/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraapp.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Gerar
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    
    
    public Window() {
        initComponents();
        
        this.btnSuma.setOpaque(false);
        this.btnSuma.setContentAreaFilled(false);
        this.btnResta.setOpaque(false);
        this.btnResta.setContentAreaFilled(false);
        this.btnMulti.setOpaque(false);
        this.btnMulti.setContentAreaFilled(false);
        this.btnDiv.setOpaque(false);
        this.btnDiv.setContentAreaFilled(false);
        this.btnClean.setOpaque(false);
        this.btnClean.setContentAreaFilled(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumUno = new javax.swing.JTextField();
        txtNumDos = new javax.swing.JTextField();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        btnClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));

        txtNumUno.setBorder(null);
        txtNumUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumUnoActionPerformed(evt);
            }
        });

        txtNumDos.setBorder(null);

        btnSuma.setForeground(new java.awt.Color(255, 255, 255));
        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoraapp/img/mas.png"))); // NOI18N
        btnSuma.setBorder(null);
        btnSuma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuma.setPreferredSize(new java.awt.Dimension(32, 32));
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoraapp/img/resta.png"))); // NOI18N
        btnResta.setBorder(null);
        btnResta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnMulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoraapp/img/multiplicar.png"))); // NOI18N
        btnMulti.setBorder(null);
        btnMulti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoraapp/img/dividir.png"))); // NOI18N
        btnDiv.setBorder(null);
        btnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblResultado.setText("    0");

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoraapp/img/limpiar.png"))); // NOI18N
        btnClean.setBorder(null);
        btnClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(txtNumUno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumDos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnResta)
                .addGap(41, 41, 41)
                .addComponent(btnMulti)
                .addGap(32, 32, 32)
                .addComponent(btnDiv)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnClean)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumUno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumDos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDiv, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMulti, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnResta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSuma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnClean)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumUnoActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:


        verified();
        numOne = Double.parseDouble(txtNumUno.getText());
        numTwo = Double.parseDouble(txtNumDos.getText());
        result = numOne + numTwo;

        lblResultado.setText(String.valueOf(result));


    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:

        verified();
        numOne = Double.parseDouble(txtNumUno.getText());
        numTwo = Double.parseDouble(txtNumDos.getText());
        result = numOne - numTwo;

        lblResultado.setText(String.valueOf(result));

    }//GEN-LAST:event_btnRestaActionPerformed

    private void verified() {
        if (txtNumUno.getText().isEmpty() && txtNumDos.getText().isEmpty() && !Double.isNaN(numOne) && Double.isNaN(numTwo)) {
            JOptionPane.showMessageDialog(rootPane,"INGRESE LOS  VALORES o numeros" );
        }
    }

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        // TODO add your handling code here:

        verified();
        numOne = Double.parseDouble(txtNumUno.getText());
        numTwo = Double.parseDouble(txtNumDos.getText());
        result = numOne * numTwo;

        lblResultado.setText(String.valueOf(result));
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:

        verified();

        try {
            numOne = Double.parseDouble(txtNumUno.getText());
            numTwo = Double.parseDouble(txtNumDos.getText());
            if (numTwo == 0){
                JOptionPane.showMessageDialog(rootPane,"No se puede dividir por cero" );
            lblResultado.setText("0");
            return;
            }

            result = numOne / numTwo;

            lblResultado.setText(String.valueOf(result));
        } catch (ArithmeticException ex) {
            JOptionPane.showMessageDialog(rootPane,"ERROR DE DIVIDENDO");
        }
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        
        txtNumUno.setText("");
        txtNumDos.setText("");
        lblResultado.setText("0");

    }//GEN-LAST:event_btnCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtNumDos;
    private javax.swing.JTextField txtNumUno;
    // End of variables declaration//GEN-END:variables

    private double numOne;
    private double numTwo;
    private double result;
}
